stages:
  - build
  - publish

variables:
  VAULT_ADDR: "https://vault.fp.unstable.life"

build_win-x86:
  tags: ["windows-mozbuild-priv"]
  stage: build
  when: manual
  before_script:
    - mkdir dist -Force | Out-Null
    - Remove-Item "$env:CI_PROJECT_DIR\dist\*" -Recurse -Force | Out-Null
    - git submodule init
    - git submodule update
  script:
    - $env:CI_COMMIT_MESSAGE=''
    - $env:CI_COMMIT_DESCRIPTION=''
    - C:\mozilla-build\start-shell-msvc2015.bat $env:CI_PROJECT_DIR\scripts\build_windows_x86.sh
    - Move-Item -Path "$env:CI_PROJECT_DIR\obj-i686-pc-mingw32\dist\flashpointnavigator-*.7z" -Destination "$env:CI_PROJECT_DIR\dist\"
  artifacts:
    expire_in: 1 week
    paths:
      - dist/flashpointnavigator*.7z

publish_win-x86:
  stage: publish
  only:
    - tags
  dependencies:
    - build_win-x86
  tags: ["windows-mozbuild-priv"]
  variables:
    GIT_STRATEGY: fetch
    GIT_CLEAN_FLAGS: none
  script:
    - $(If (-Not [regex]::IsMatch("$CI_COMMIT_TAG", "^v[0-9]{4}\.[0-9]{2}\.[0-9]{2}$")) {exit})
    - $env:VAULT_TOKEN = (vault.exe write -field=token auth/jwt/login role=fpbrowser-nexus-read jwt="${CI_JOB_JWT}")
    - $NEXUS_USERNAME = (vault.exe kv get -field=username flashpoint/nexus)
    - $NEXUS_PASSWORD = (vault.exe kv get -field=password flashpoint/nexus)
    - $NEXUS_SERVER = (vault.exe kv get -field=server flashpoint/nexus)
    - $NEXUS_REPOSITORY = "flashpoint-dependency-software"
    - $UPLOAD_PATH = "FlashpointNavigator"
    - $filename = "FlashpointNavigator-win-x86-release-$CI_COMMIT_TAG"
    - $env:MOZ_SIMPLE_PACKAGE_NAME = $filename
    - $env:CI_COMMIT_MESSAGE=''
    - C:\mozilla-build\start-shell-msvc2015.bat $env:CI_PROJECT_DIR\scripts\publish.sh
    - Move-Item -Path "$env:CI_PROJECT_DIR\obj-i686-pc-mingw32\dist\$filename.7z" -Destination "$env:CI_PROJECT_DIR\dist\$filename.7z"
    - '& "curl.exe" -s -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" --upload-file "$env:CI_PROJECT_DIR\dist\$filename.7z" "https://${NEXUS_SERVER}/repository/${NEXUS_REPOSITORY}/${UPLOAD_PATH}/$filename.7z"'
    - Remove-Item -Path "$env:CI_PROJECT_DIR\dist\$filename.7z"
